# -*- coding: utf-8 -*-
"""Program 4.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_62xEFFOUqmSHFce1msQzu3_9ywCdZWX

# Write a  python progarm to swap two variables
"""

# Input two variables
a = input("Enter the value of the first variable(a): ")
b = input("Enter the value of the second variable(b): ")
#Dispaly the original value
print(f"Original values: a = {a},b = {b}")
#Swap the values using a temporary variable
temp = a
a = b
b = temp
# Display the swapped values
print(f"Swapped values: a = {a}, b={b}")